"""se le agrego el unique al nombre de Alimentacion

Revision ID: 777f76d6da50
Revises: b4be51d03a87
Create Date: 2026-07-21 11:46:42.935809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models


# revision identifiers, used by Alembic.
revision: str = '777f76d6da50'
down_revision: Union[str, Sequence[str], None] = 'b4be51d03a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alimentaciones', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alimentaciones', type_='unique')
    # ### end Alembic commands ###
