"""fix models

Revision ID: b4be51d03a87
Revises: cdfb4dada229
Create Date: 2026-07-18 02:55:53.918512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models


# revision identifiers, used by Alembic.
revision: str = 'b4be51d03a87'
down_revision: Union[str, Sequence[str], None] = 'cdfb4dada229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
